### ISSUE TITLE
Pacific-centric Robinson projection support

### ISSUE THREAD

**Issue by danielsms** [KNMI/adaguc-server#148]
Hi,

I would like to plot the following NetCDF file [sample_tas_cmip6_ssp585_preIndustrial_warming2_year.nc.zip](https://github.com/KNMI/adaguc-server/files/5546888/sample_tas_cmip6_ssp585_preIndustrial_warming2_year.nc.zip) using a Pacific-centric Robinson projection.

By using the standard Robinson projection defined as ```<Projection id="EPSG:54030" proj4="+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs "/>``` ADAGUC generetes a perfect image: ![robinson_standard_ok](https://user-images.githubusercontent.com/6248288/99265378-ecfd7f00-2821-11eb-800a-5ef21e8d961e.png)

However, if I try with the Pacific-centric version defined as ```<Projection id="EPSG:54030pc" proj4="+proj=robin +lon_0=-150 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs "/>``` the resulting image has some problems for positive longitudes: ![robinson_offset_fail](https://user-images.githubusercontent.com/6248288/99265637-32ba4780-2822-11eb-8ea6-9f0dacaa90c4.png)

As far as I know, there is not an EPSG code for the Pacific-centric Robinson projection. So, following [some examples](https://gis.stackexchange.com/questions/70411/displaying-world-country-shapefiles-centered-on-pacific-ocean-using-robinson-or), I've just included an offset in the ```+lon_0``` proj parameter and changed the projection name. I've tried this same proj definition with some GeoJSON files and it works well. So, I would say the proj definition is correct.

I've also tried with the ```+over``` [proj parameter](https://proj.org/usage/projections.html#longitude-wrapping): in this case ADAGUC properly handles positive longitudes but the map is not centered in the Pacific: ![robinson_over_fail](https://user-images.githubusercontent.com/6248288/99266043-a5c3be00-2822-11eb-8d95-d3330b0cc0fa.png)

Please, could you tell me if ADAGUC supports offsets in this ```+lon_0``` parameter?

Thank you for sharing this great tool with the climate software community!

**Comment by maartenplieger** [comment]
Thanks Daniel! That does not look as it should. We will have a look.

**Comment by danielsms** [comment]
Great! Thank you @maartenplieger !

**Comment by maartenplieger** [comment]
Possibly solved in https://github.com/KNMI/adaguc-server/pull/150

![image](https://user-images.githubusercontent.com/8201298/99537240-b5224300-29ab-11eb-8091-f47f4bf702ba.png)

BTW: you can test any Proj4 projection string in the WMS GetMap URL using the following:

```&CRS=PROJ4:%2Bproj%3Drobin %2Blon_0%3D-150 %2Bx_0%3D0 %2By_0%3D0 %2Bellps%3DWGS84 %2Bdatum%3DWGS84 %2Bunits%3Dm %2Bno_defs%20```

This is based on the projection string ```+proj=robin +lon_0=-150 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs```

**Comment by danielsms** [comment]
Hi Martin, I confirm it works!

![robinson_offset_ok](https://user-images.githubusercontent.com/6248288/99562851-e4937880-29c8-11eb-8967-ecd9cf1dba14.png)

Thank you for your support!

**Comment by kktuax** [comment]
Dear Maarten

We have recently noticed that after the fix another two custom projections that we were using are now presenting issues such as this: 

![image](https://user-images.githubusercontent.com/3185625/113136585-d4679180-9223-11eb-8c10-63547efa9bfb.png)

We are using `openearth/adaguc-server:2.5.6` and have the projections defined in the `<Configuration>` like this:

```xml
<Projection id="EPSG:3413" proj4="+proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"/>
<Projection id="EPSG:3412" proj4="+proj=stere +lat_0=-90 +lat_ts=-70 +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378273 +b=6356889.449 +units=m +no_defs"/>
```
In the attached example, using the autowms feature: when providing the proj in the CRS parameter we get the following image 

![image](https://user-images.githubusercontent.com/3185625/113136928-3627fb80-9224-11eb-8d93-1e75138d6997.png)

https://localhost/adaguc-services/wms?source=sample_tas_cmip6_ssp585_preIndustrial_warming2_year.nc&SERVICE=WMS&version=1.1.1&service=WMS&request=getMap&layers=tas&format=image%2Fpng&srs=%2Bproj%3Dstere+%2Blat_0%3D-90+%2Blat_ts%3D-70+%2Blon_0%3D0+%2Bk%3D1+%2Bx_0%3D0+%2By_0%3D0+%2Ba%3D6378273+%2Bb%3D6356889.449+%2Bunits%3Dm+%2Bno_defs&width=800&height=600

**Comment by maartenplieger** [comment]
Fixed (hopefully) in version 2.5.9:

- Robinson projection (source=test/sample_tas_cmip6_ssp585_preIndustrial_warming2_year.nc&SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=tas&WIDTH=600&HEIGHT=300&CRS=EPSG%3A54030&BBOX=-17002000,-8700000,17002000,8700000&STYLES=auto/nearest&FORMAT=image/png32&TRANSPARENT=FALSE)
![test_WMSGetMapRobinsonProjection_sample_tas_cmip6_ssp585_preIndustrial_warming2_year](https://user-images.githubusercontent.com/8201298/117792185-58f9f680-b24b-11eb-8499-610de42ef1e0.png)

- Custom EPSG:3412 projection (source=test/sample_tas_cmip6_ssp585_preIndustrial_warming2_year.nc&SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=tas,geojsonoverlay&&format=image%2Fpng32&crs=%2Bproj%3Dstere+%2Blat_0%3D-90+%2Blat_ts%3D-70+%2Blon_0%3D0+%2Bk%3D1+%2Bx_0%3D0+%2By_0%3D0+%2Ba%3D6378273+%2Bb%3D6356889.449+%2Bunits%3Dm+%2Bno_defs&width=800&height=600&BBOX=-4630165.372231959,-4523993.082972504,5384973.558397711,4717659.691530302&)
![test_WMSGetMapCustomCRSEPSG3412Projection_sample_tas_cmip6_ssp585_preIndustrial_warming2_year](https://user-images.githubusercontent.com/8201298/117792361-7f1f9680-b24b-11eb-8038-6cc713510df7.png)

- Custom EPSG:3413 projection  (source=test/sample_tas_cmip6_ssp585_preIndustrial_warming2_year.nc&SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=tas,geojsonoverlay&&format=image%2Fpng32&crs=%2Bproj%3Dstere%20%2Blat_0%3D90%20%2Blat_ts%3D70%20%2Blon_0%3D-45%20%2Bk%3D1%20%2Bx_0%3D0%20%2By_0%3D0%20%2Bdatum%3DWGS84%20%2Bunits%3Dm%20%2Bno_defs&width=800&height=600&BBOX=-4630165.372231959,-4523993.082972504,5384973.558397711,4717659.691530302&)
![test_WMSGetMapCustomCRSEPSG3413Projection_sample_tas_cmip6_ssp585_preIndustrial_warming2_year](https://user-images.githubusercontent.com/8201298/117792456-952d5700-b24b-11eb-93b4-335a08e5ce9a.png)

**Comment by kktuax** [comment]
Thank you for your feedback Maarten

You are right, with the example attached in the ticket the maps seem fine. However, we are still having the issue with a lower-res CMIP5 dataset: [ipcc-cmip5-tas-historical_subset.nc.zip](https://github.com/KNMI/adaguc-server/files/6459157/ipcc-cmip5-tas-historical_subset.nc.zip)

http://localhost:8080/adaguc-services/wms?source=ipcc-cmip5-tas-historical_subset.nc&SERVICE=WMS&version=1.1.1&service=WMS&request=getMap&layers=tas&format=image%2Fpng&srs=%2Bproj%3Dstere+%2Blat_0%3D90+%2Blat_ts%3D70+%2Blon_0%3D-45+%2Bk%3D1+%2Bx_0%3D0+%2By_0%3D0+%2Bdatum%3DWGS84+%2Bunits%3Dm+%2Bno_defs&width=800&height=600&bbox=-4630165.372231959%2C-4523993.082972504%2C5384973.558397711%2C4717659.691530302

![image](https://user-images.githubusercontent.com/3185625/117816943-60c79400-b267-11eb-8706-f7b3e001d874.png)

The weird effect appears both in 2.5.6 and 2.5.9

**Comment by maartenplieger** [comment]
Will look in to this one too.

**Comment by maartenplieger** [comment]
See PR: https://github.com/KNMI/adaguc-server/pull/164/files, version 2.5.10 (pushed to dockerhub)

A small fix and more tests are added, also with the newly provided dataset (thanks for that). I think these all seem to work well now. There was also a small issue in the previous rendering, which is improved too.

**Comment by maartenplieger** [comment]
![test_WMSGetMapCustomCRSEPSG3412Projection_ipcc_cmip5_tas_historical_subset nc](https://user-images.githubusercontent.com/8201298/117966003-b792a380-b323-11eb-93ca-136d54c411d3.png)
![test_WMSGetMapCustomCRSEPSG3413Projection_ipcc_cmip5_tas_historical_subset nc](https://user-images.githubusercontent.com/8201298/117966007-b82b3a00-b323-11eb-9a1e-852a88e7113c.png)
![test_WMSGetMapRobinsonProjection_ipcc_cmip5_tas_historical_subset nc](https://user-images.githubusercontent.com/8201298/117966009-b82b3a00-b323-11eb-9570-82cfe8b0a3ad.png)

**Comment by kktuax** [comment]
Thank you Maarten! Now both datasets work fine with the stereographic projections.

However I'm afraid we may have a regression issue: I think the pacific centric projection gives again strange results:

http://localhost:8080/adaguc-services/wms?source=ipcc-cmip5-tas-historical_subset.nc&SERVICE=WMS&version=1.1.1&service=WMS&request=getMap&layers=tas&format=image%2Fpng&srs=%2Bproj%3Drobin+%2Blon_0%3D-150+%2Bx_0%3D0+%2By_0%3D0+%2Bellps%3DWGS84+%2Bdatum%3DWGS84+%2Bunits%3Dm+%2Bno_defs&width=800&height=600

![image](https://user-images.githubusercontent.com/3185625/117967959-f295d680-b325-11eb-8b0a-f1222d8fba2b.png)

This happens on the two examples, It doesn't seem to be related to the resolution.

Can you please include a test for that projection as well? Thanks again for all your efforts

**Comment by maartenplieger** [comment]
Will do!!! :D

**Comment by maartenplieger** [comment]
Somehow the test in docker gives slightly different results than on my workstation. A few pixels differ, I think this has to do with difference in proj4 versions.

Can you check if it is working in 2.5.11 ?
![image](https://user-images.githubusercontent.com/8201298/117992408-32b58300-b33f-11eb-89b9-de103c56577b.png)

**Comment by kktuax** [comment]
Thank you Maarten, you are the best! All 3 projections are working fine with 2.5.11

**Comment by maartenplieger** [comment]
Good to hear! :+1:
